--!strict
-- Tension Doubles: PINTO HARE! / Roblox ver0.6.1
-- Serve Balance Patch: serves now have their own tuned speed/arc so they reach the opponent court.

local Config = {
	Version = "0.6.1",
	Title = "Tension Doubles: PINTO HARE!",
	Subtitle = "Hold PIN. Sync for HARE.",
	MaterialName = "Tension Fiber",
	ScoreToWin = 7,

	-- Court dimensions in studs.
	CourtWidth = 56,
	CourtDepth = 34, -- per side, from center line to back court line
	OutZoneDepth = 8,
	WallHeight = 3,

	-- Player movement. Slightly faster so touch players can recover.
	WalkSpeed = 20,
	JumpHeight = 4.5,
	ClampPlayersToCourt = true,

	-- Dev/testing. Change only LivePreset for solo / 2-player / 4-player live tests.
	LivePreset = "Solo",
	LivePresets = {
		Solo = {
			AllowGhostPartners = true,
			GhostMirrorsPinning = true,
			SoloGhostsMirrorPinning = true,
			CpuFillEnabled = true,
			MinPlayersToAutoStart = 1,
		},
		TwoPlayer = {
			AllowGhostPartners = true,
			GhostMirrorsPinning = true,
			SoloGhostsMirrorPinning = false,
			CpuFillEnabled = true,
			MinPlayersToAutoStart = 2,
		},
		FourPlayer = {
			AllowGhostPartners = false,
			GhostMirrorsPinning = false,
			SoloGhostsMirrorPinning = false,
			CpuFillEnabled = false,
			MinPlayersToAutoStart = 4,
		},
	},

	-- Applied by LivePreset below. Keep these as readable fallbacks for Studio autocomplete.
	AllowGhostPartners = true,
	GhostMirrorsPinning = true,
	SoloGhostsMirrorPinning = true,
	MinPlayersToAutoStart = 1,
	LobbyReadyEnabled = true,
	LobbySpawnPosition = Vector3.new(0, 3, -116),
	LobbyCameraFocusPosition = Vector3.new(0, 1.2, -92),
	LobbyCameraBack = 74,
	LobbyCameraHeight = 72,
	LobbyCameraFov = 61,
	CourtSelections = {
		{ Id = "Grass", Label = "Grass Court", X = 0, Color = Color3.fromRGB(96, 185, 58) },
		{ Id = "Rooftop", Label = "Rooftop Court", X = 300, Color = Color3.fromRGB(76, 96, 112) },
		{ Id = "School", Label = "School Court", X = 600, Color = Color3.fromRGB(218, 178, 86) },
		{ Id = "Festival", Label = "Festival Court", X = 900, Color = Color3.fromRGB(224, 86, 116) },
		{ Id = "Space", Label = "Space Court", X = 1200, Color = Color3.fromRGB(72, 62, 152) },
	},
	ArenaFolderName = "Arenas",
	GrassTileArena = {
		Enabled = true,
		CourtId = "Grass",
		ModelName = "Arena_Grass",
		LegacyModelName = "TDArena_TileField64",
		SizeStuds = 88,
		ModelWaitSeconds = 3,
		BuilderScriptPath = "scripts/roblox/build_tile_field_64_arena.server.lua",
		SourceDataPath = "data/arena/tile-field-64-arena.json",
	},
	CourtArenaModels = {
		Grass = {
			Enabled = true,
			ModelName = "Arena_Grass",
			LegacyModelName = "TDArena_Grass64",
			SizeStuds = 88,
			SourceImagePath = "assets/ChatGPT Image 2026年6月2日 19_40_15.png",
		},
		Rooftop = {
			Enabled = true,
			ModelName = "Arena_Rooftop",
			LegacyModelName = "TDArena_Rooftop64",
			SizeStuds = 88,
			SourceImagePath = "assets/ChatGPT Image 2026年6月2日 19_40_24.png",
		},
		School = {
			Enabled = true,
			ModelName = "Arena_School",
			LegacyModelName = "TDArena_School64",
			SizeStuds = 88,
			SourceImagePath = "assets/ChatGPT Image 2026年6月2日 19_40_35.png",
		},
		Festival = {
			Enabled = true,
			ModelName = "Arena_Festival",
			LegacyModelName = "TDArena_Festival64",
			SizeStuds = 88,
			SourceImagePath = "assets/ChatGPT Image 2026年6月2日 19_40_43.png",
		},
		Space = {
			Enabled = true,
			ModelName = "Arena_Space",
			LegacyModelName = "TDArena_Space64",
			SizeStuds = 88,
			SourceImagePath = "assets/ChatGPT Image 2026年6月2日 19_40_54.png",
		},
	},
	CpuFillEnabled = true,
	CpuFillPartnerVisible = true,
	CpuFillLabelText = "CPU",
	CpuFillPartSize = 2.2,
	CpuFillMoveSpeed = 18,
	CpuFillNetSpan = 14,
	CpuFillCourtZ = 18,
	CpuFillBallTrackZOffset = 5,
	CpuFillReactionDelay = 0.22,
	CpuFillAimError = 2.8,
	CpuFillReactionDistance = 18,
	CpuFillAutoPinChance = 0.58,
	CpuFillAutoPinLeadTime = 1.25,
	CpuFillPinDecisionInterval = 0.34,
	CpuFillPinCooldown = 0.72,

	-- Ball. v0.5.2 lowers PIN/HARE arcs so strong returns land in court more often.
	BallRadius = 1.72,
	BallMinSpeed = 18,
	BallBaseSpeed = 29,
	BallServeSpeed = 40,
	ServeStartZ = 7.5,
	ServeVerticalVelocity = 5.2,
	ServeLateralMax = 4.5,
	ServeChargeEnabled = true,
	ServeHarePinDelta = 0.38,
	ServeHareSpeed = 47,
	ServeHareVerticalVelocity = 3.7,
	ServeHareLateralMax = 2.0,
	ServeChargedSpeed = 43,
	ServeChargedVerticalVelocity = 4.6,
	ServeChargedLateralMax = 3.2,
	ServeOnePinSpeed = 42,
	ServeOnePinVerticalVelocity = 4.8,
	ServeOnePinLateralMax = 7.2,
	ServeSlackSpeed = 34,
	ServeSlackVerticalVelocity = 7.4,
	ServeSlackLateralMax = 2.4,
	ServeOverTensionSpeed = 44,
	ServeOverTensionVerticalVelocity = 3.8,
	ServeOverTensionLateralMax = 8.4,
	BallMaxSpeed = 58,
	BallGravity = 42,
	ServeHeight = 8,
	ReturnLift = 0.52,

	-- Net hit detection. Larger hit radius for touch/mobile readability.
	NetVisualHeight = 3.2,
	NetHitRadius = 3.75,
	NetMinHeight = 1.3,
	NetMaxHeight = 9.8,

	-- Tension distance bands. Distance is between the two net endpoints.
	SlackDistance = 8,
	GoodDistanceMin = 8,
	GoodDistanceMax = 18,
	OverDistanceMin = 16,
	BrokenDistance = 23,

	-- Hit windows. A little kinder on mobile.
	HitCooldown = 0.25,
	HarePinDelta = 0.30,
	HareContactWindow = 0.45,
	HareHoldWindow = 3.5,
	HareRequiresFreshPin = false,

	-- v0.5.2 Return Balance Patch. Keep PIN fun without making every good hit fly OUT.
	PowerBonusSlack = -8,
	PowerBonusNormal = 1,
	PowerBonusOverTension = 6,
	PowerBonusBothPin = 7,
	PowerBonusOnePin = 3,
	PowerBonusHare = 8,
	ReturnLiftSlack = 0.38,
	ReturnLiftNormal = 0.68,
	ReturnLiftOnePin = 0.56,
	ReturnLiftOverTension = 0.20,
	ReturnLiftHare = 0.24,
	ForwardSpeedCapEnabled = true,
	ReturnMaxForwardSpeed = 34,
	PinMaxForwardSpeed = 42,
	HareMaxForwardSpeed = 40,
	OnePinMaxForwardSpeed = 43,
	OverTensionMaxForwardSpeed = 40,
	SlackMaxForwardSpeed = 28,
	EarlyRallyAssistHits = 2,
	EarlyRallyAssistForwardCap = 34,
	EarlyRallyAssistLiftFloor = 0.46,
	EarlyRallyAssistPowerTrim = 2,

	-- Match pacing.
	PointDelay = 1.45,
	PreMatchReadyTime = 2.6,
	CountdownTime = 3,
	GameOverDelay = 3.5,

	-- Visuals. Thicker Beam and clearer ball for phone screens.
	BeamWidth = 2.2,
	BeamTextureSpeed = 1.8,
	BeamCurveSlack = 5.4,
	BeamCurveNormal = 0,
	BeamCurveOverTension = -1.1,
	BeamCurveHare = 0,
	BeamWidthSlack = 1.45,
	BeamSlackTransparency = 0.24,
	BeamWidthOverTension = 1.85,
	BeamWidthHareBonus = 1.18,
	BeamHareTransparency = 0.0,
	OverTensionWobbleScale = 0.42,
	SlackAbsorbRippleSize = 12,
	SlackAbsorbRippleDuration = 0.44,
	HareHardeningRingSize = 16,
	HareHardeningRingDuration = 0.30,
	HareGlowBrightness = 4.4,
	HareTrailLifetime = 0.56,
	HareSparkColumnHeight = 18,
	HareSparkColumnWidth = 1.4,
	HareSparkColumnDuration = 0.34,
	BallReadabilityHaloSize = 4.4,
	BallReadabilityHaloTransparency = 0.62,
	BallReadableGlowBrightness = 3.4,
	BallReadableGlowRange = 22,
	BallTrailLifetime = 0.50,
	HudMessageDuration = 1.25,
	MobilePinButtonScale = 0.20,

	-- v0.3 party polish.
	RallySpeedBonusPerHit = 0.65,
	RallySpeedBonusMax = 5,
	HareScreenShakePower = 1,
	PinRingRadius = 4.2,
	PinRingHeight = 0.12,
	WaitingMessage = "Waiting for players...",
	LobbyWaitingReadyMessage = "Ready up!",
	LobbyChooseCourtMessage = "READY starts on the selected theme. Court theme is optional.",
	LobbyHelpMessage = "Step on PRACTICE, QUICK 2v2, or FRIENDS. Or press READY now.",
	LobbyRulesText = "Move. Stretch. Hold PIN together.",
	LobbyTutorialBoardTitle = "HOW TO PLAY",
	LobbyTutorialBoardSubtitle = "TENSION DOUBLES: PINTO HARE!",
	LobbyTutorialStepMove = "1  MOVE WITH YOUR PARTNER",
	LobbyTutorialStepStretch = "2  STRETCH THE FIBER",
	LobbyTutorialStepPin = "3  HOLD PIN TOGETHER FOR HARE!",
	LobbyTutorialBoardXOffset = -27,
	LobbyTutorialBoardZOffset = 6,
	LobbyFlowHelpText = "1 Mode pad.  2 Theme optional.  3 READY.",
	LobbyModeBoardTitle = "1  CHOOSE MODE",
	LobbyCourtBoardTitle = "2  OPTIONAL COURT THEME",
	LobbyReadyBoardTitle = "3  PRESS READY",
	LobbyModePadZOffset = 12,
	LobbyReadyBoardZOffset = 24,
	LobbyCourtBoardZOffset = 36,
	LobbyEntryPadTouchJoinEnabled = true,
	LobbyParticipantCountFormat = "Players %d / Ready %d",
	LobbySpectatorLabel = "SPECTATE",
	LobbySpectatorHelp = "Watch the next match from here.",
	LobbyEntryPromptActionText = "Join",
	LobbyEntrySelectedMessageFormat = "%s selected. Press READY.",
	LobbyHudGuideTitle = "JOIN MATCH",
	LobbyHudModeStep = "1  MODE PAD or READY",
	LobbyHudThemeStepFormat = "2  THEME: %s",
	LobbyHudReadyStepFormat = "3  READY: %d/%d players",
	LobbyHudWaitingStep = "CPU fills empty slots while players join.",
	LobbyGuideStepSeconds = 2.25,
	LobbyGuideStepModeText = "1  CHOOSE MODE",
	LobbyGuideStepThemeText = "2  PICK THEME",
	LobbyGuideStepReadyText = "3  PRESS READY",
	LobbyGuideCompactText = "Mode. Theme. READY.",
	LobbyModeSummaryFormat = "MODE: %s",
	LobbyThemeSummaryFormat = "THEME: %s",
	LobbyDefaultModeLabel = "Quick 2v2",
	LobbyMainButtonY = 0.545,
	LobbyMainButtonWidthTouch = 0.34,
	LobbyMainButtonWidthDesktop = 0.24,
	LobbyMainButtonHeightTouch = 0.105,
	LobbyMainButtonHeightDesktop = 0.085,
	LobbyGuideYTouchPortrait = 0.690,
	LobbyGuideYTouchLandscape = 0.700,
	LobbyGuideYDesktop = 0.700,
	LobbyGuideWidthTouchPortrait = 0.84,
	LobbyGuideWidthTouchLandscape = 0.62,
	PracticeVsBotsButtonLabel = "Practice vs Bots",
	PracticeWallEnabled = true,
	PracticeWallTitle = "PRACTICE WALL",
	PracticeWallHelp = "Hit PIN!  Try HARE!",
	PracticeWallPromptActionText = "Practice",
	PracticeWallPromptObjectText = "Practice Wall",
	PracticeWallCooldownSeconds = 0.75,
	PracticeWallBallTravelSeconds = 0.42,
	PracticeWallPinEvery = 1,
	PracticeWallHareEvery = 3,
	PracticeWallXOffset = 30,
	PracticeWallZOffset = 42,
	LobbyEntryPads = {
		{
			Id = "Practice",
			Label = "PRACTICE",
			SubLabel = "1P + CPU",
			CourtId = "Grass",
			X = -20,
			Color = Color3.fromRGB(255, 226, 118),
		},
		{
			Id = "Quick2v2",
			Label = "QUICK 2v2",
			SubLabel = "Players + CPU fill",
			CourtId = "Grass",
			X = 0,
			Color = Color3.fromRGB(111, 210, 168),
		},
		{
			Id = "PrivateFriends",
			Label = "PRIVATE / FRIENDS",
			SubLabel = "Play with friends",
			CourtId = "Grass",
			X = 20,
			Color = Color3.fromRGB(130, 170, 255),
		},
	},
	CourtSelectBoardTitle = "OPTIONAL COURT THEME",
	CourtSelectBoardHelp = "Theme only. Skip it and press READY.",
	CourtPromptActionText = "Choose",
	CourtSelectedMessageFormat = "%s selected. Press READY.",
	CourtReturnPromptActionText = "Lobby",
	CourtReturnPromptObjectText = "Back to Lobby",
	CourtReturnMessage = "Back in lobby. Press READY, or pick a mode/theme first.",
	MatchSpawnHeightOffset = 2.5,
	MatchPreviewPadHiddenTransparency = 0.82,
	CourtUnavailableMessage = "That court is playing!",
	LobbyReadySubMessage = "READY starts match. Mode/theme optional.",
	LobbyAllReadyMessage = "All ready!",
	MatchReadyMessage = "GET READY",
	MatchReadySubMessage = "Find your spot. Watch the first serve.",
	StartMessage = "PINTO HARE!",
	WaitingSubMessage = "Make a net. Hold PIN. Sync HARE.",
	CpuFillMatchSubMessage = "CPU fills empty slots. Jump in anytime!",
	GameOverSubMessage = "NEXT MATCH INCOMING!",
	FailSubtitleDropText = "LANDING MISSED!",
	FailSubtitleOutText = "TOO MUCH POWER!",
	TeamSideLabelEnabled = true,
	TeamSideLabelSize = 13,
	TeamSpawnRingSize = 7.8,
	ProgressLiteEnabled = true,
	ProgressStatWins = "Wins",
	ProgressStatHares = "HAREs",
	ProgressStatBestRally = "Best Rally",
	ProgressStatTeamSyncs = "Team Syncs",
	ProgressStatDailyBoosts = "Daily Boosts",
	ProgressStatTitle = "Title",
	ProgressTitleDefault = "Rally Starter",
	ProgressTitleHareRookie = "HARE Rookie",
	ProgressTitleSyncPartner = "Sync Partner",
	ProgressTitleHareRookieAt = 1,
	ProgressTitleSyncPartnerAt = 3,
	DailyBoostEnabled = true,
	DailyBoostBoardTitle = "DAILY BOOST",
	DailyBoostBoardHelp = "Hit 1 HARE + Rally 4 to earn a Boost.",
	DailyBoostHudFormat = "Daily: HARE %d/%d  Rally %d/%d",
	DailyBoostCompleteText = "Daily Boost ready!",
	DailyBoostEarnedMessage = "DAILY BOOST EARNED!",
	DailyBoostEarnedSubMessage = "Nice teamwork. Queue another round!",
	DailyBoostHareTarget = 1,
	DailyBoostRallyTarget = 4,
	FiberSkinsEnabled = true,
	FiberSkinBlend = 0.36,
	FiberSkinDefaultColor = Color3.fromRGB(245, 245, 255),
	FiberSkinHareRookieColor = Color3.fromRGB(255, 218, 92),
	FiberSkinSyncPartnerColor = Color3.fromRGB(112, 245, 208),
	FiberSkinOnePinColor = Color3.fromRGB(255, 170, 90),
	MonetizationLiteEnabled = true,
	SupporterPassId = 0,
	FiberColorPackPassId = 0,
	HareFxPackPassId = 0,
	MonetizationShopTitle = "COSMETIC SHOP",
	MonetizationShopSubtitle = "Style only. No power boosts.",
	MonetizationStandTitle = "COSMETIC SHOP",
	MonetizationStandHelp = "Fiber colors and HARE FX. No pay-to-win.",
	MonetizationPromptActionText = "Shop",
	MonetizationUnavailableMessage = "Pass IDs are not set yet.",
	MonetizationOwnedLabel = "OWNED",
	MonetizationBuyLabel = "BUY",
	ServerMissingMessage = "SERVER SCRIPT MISSING",
	ServerMissingSubMessage = "Import TDServer into ServerScriptService, then Play again.",
	AudioMixerEnabled = true,
	MusicSoundGroupName = "TDMusic",
	SfxSoundGroupName = "TDSFX",
	UiSoundGroupName = "TDUI",
	MusicDefaultVolume = 0.55,
	SfxDefaultVolume = 0.70,
	UiDefaultVolume = 0.65,
	AudioVolumeStep = 0.10,
	AudioMixerTopRightX = 0.985,
	AudioMixerMusicY = 0.075,
	AudioMixerSfxY = 0.140,
	AudioSfxSoundIds = {
		Pin = "rbxassetid://12221990",
		Hare = "rbxassetid://12221831",
		OnePin = "rbxassetid://12221990",
		Slack = "rbxassetid://12221990",
		OverTension = "rbxassetid://12222216",
		Broken = "rbxassetid://12222216",
		Out = "rbxassetid://12222216",
		Score = "rbxassetid://12221831",
		Countdown = "rbxassetid://12221944",
		Start = "rbxassetid://12221831",
		UiClick = "rbxassetid://12221990",
	},
	BgmVolumeControlEnabled = true,
	BgmDefaultVolume = 0.55,
	BgmVolumeStep = 0.10,
	BgmPanelTitle = "MUSIC",
	SfxPanelTitle = "SFX",
	AudioMixerHideDuringMatch = true,
	AudioMixerVisibleStates = {
		Lobby = true,
		WaitingForPlayers = true,
		GameOver = true,
	},
	BgmMissingMessage = "BGM sound not found",
	BgmSoundNames = {
		"BGM",
		"Music",
		"BackgroundMusic",
		"TD_BGM",
	},
	MonetizationProducts = {
		{
			Key = "Supporter",
			Name = "Supporter Pass",
			PassIdKey = "SupporterPassId",
			Description = "A small badge of support in the lobby.",
		},
		{
			Key = "FiberColorPack",
			Name = "Fiber Color Pack",
			PassIdKey = "FiberColorPackPassId",
			Description = "Extra Tension Fiber color choices.",
		},
		{
			Key = "HareFxPack",
			Name = "HARE FX Pack",
			PassIdKey = "HareFxPackPassId",
			Description = "Alternate HARE hit text and trail style.",
		},
	},
	LateJoinSpectatorEnabled = true,
	SpectatorTeamName = "Spectators",
	LateJoinSpectatorMessage = "NEXT MATCH QUEUE",
	LateJoinSpectatorSubMessage = "Match in progress. You are queued for the next match.",
	NextMatchQueuedMessage = "Queued for next match",
	AfkSafetyEnabled = true,
	LobbyReadyAfkSeconds = 90,
	PinHoldAfkReleaseSeconds = 12,
	AfkReadyClearedMessage = "READY cleared after inactivity.",
	MatchResultsEnabled = true,
	MatchResultsHaresLabel = "HAREs",
	MatchResultsBestRallyLabel = "Best Rally",
	MatchResultsTeamSyncsLabel = "Team Syncs",
	MatchResultsSlackSavesLabel = "Slack Saves",
	MatchResultsShortBestRallyLabel = "Rally",
	MatchResultsShortTeamSyncsLabel = "Syncs",
	GameOverResultsHeight = 0.120,
	GameOverResultsTextSizeDesktop = 19,
	GameOverResultsTextSizeTouch = 16,
	AnalyticsLiteEnabled = true,
	AnalyticsLiteFolderName = "TensionDoublesAnalytics",
	AnalyticsLitePrintEnabled = false,
	AnalyticsLiteEvents = {
		LobbyEntered = "LobbyEntered",
		PracticeStarted = "PracticeStarted",
		FirstReady = "FirstREADY",
		FirstPin = "FirstPIN",
		FirstHare = "FirstHARE",
		MatchCompleted = "MatchCompleted",
	},
	-- Studio-only local diagnostics. Set false to remove the replicated inspection surface.
	StudioDiagnosticsEnabled = true,
	StudioDiagnosticsFolderName = "TensionDoublesStudioDiagnostics",

	-- v0.4 Court & Juice Patch.
	CourtJuiceEnabled = true,
	HareFreezeTime = 0.105, -- tiny hit-stop after a HARE return
	HareComboWindow = 7.0,
	HareShockwaveSize = 22,
	HareShockwaveDuration = 0.52,
	PointBurstSize = 15,
	PointBurstDuration = 0.42,
	LandingTargetEnabled = true,
	LandingTargetUpdateInterval = 0.08,
	LandingTargetMaxPredictionTime = 2.4,
	LandingTargetSize = 8.0,
	LandingTargetThickness = 0.09,
	LandingTargetInColor = Color3.fromRGB(255, 240, 130),
	LandingTargetOutColor = Color3.fromRGB(255, 80, 80),
	LandingTargetTransparency = 0.12,
	LandingTargetOutTransparency = 0.05,
	ArenaGlowPulseDuration = 0.55,
	CrowdDotCountPerSide = 14,
	CenterEmblemSize = 8.4,
	CenterEmblemTransparency = 0.82,
	CrowdWaveDelayPerDot = 0.028,
	CrowdWaveDuration = 0.42,
	ShowRallyOnPointAt = 4,

	-- v0.5 Onboarding & Feel Patch.
	OnboardingEnabled = true,
	OnboardingStepDuration = 1.35,
	First30OnboardingSteps = {
		"Make a Tension Fiber net with your partner.",
		"CPU fills empty slots until players join.",
		"Move apart until it says TENSION OK.",
		"Hold PIN together to spark HARE!",
	},
	CpuFillIntroText = "CPU partners are filling empty slots.",
	ServingSubMessage = "Track the ball!",
	ServeChargeMessage = "FIBER CHARGE!",
	ServeChargeSubMessage = "Hold PIN together before serve.",
	ServeOwnerMessageFormat = "%s SERVES",
	ServeOwnerSubMessageFormat = "%s has serve. Hold PIN to charge.",
	ServeBallLabelText = "SERVE",
	ServeHareMessage = "HARE SERVE!",
	ServeChargedMessage = "SYNC SERVE!",
	ServeOnePinMessage = "SLICE SERVE!",
	ServeSlackMessage = "SAFE FLOAT SERVE!",
	ServeOverTensionMessage = "WILD SERVE!",
	FinalHareEnabled = true,
	FinalHareMessage = "FINAL HARE!",
	FinalHareServeMessageFormat = "%s FINAL SERVE",
	FinalHareSubMessage = "Next point wins.",
	RallySubMessage = "",
	PointSubMessage = "NEXT SERVE!",
	HareSubtitleText = "TEAM SYNC!",
	FirstHareCelebrationEnabled = true,
	FirstHareMessage = "FIRST HARE!",
	FirstHareSubtitle = "YOUR FIRST TEAM SYNC!",
	HareHitTextComboSuffixFormat = " x%d",
	HareFxY = 0.365,
	HitFxY = 0.500,
	HareHitTextStyles = {
		{ AtCombo = 1, Text = "HARE!!" },
		{ AtCombo = 2, Text = "DOUBLE HARE!!" },
		{ AtCombo = 4, Text = "HARE STREAK!!" },
	},
	TouchHint = "Move. Stretch. Hold PIN.",
	TouchLandscapeHint = "Move. Stretch. Hold PIN.",
	TouchPortraitHint = "Rotate sideways for best play.",
	DesktopHint = "Hold E / Space: PIN",
	GamepadHint = "Hold R2: PIN",
	NetGuideMakeText = "MAKE A NET",
	NormalHitText = "FIBER HIT!",
	NetGuideGoodText = "TENSION OK",
	NetGuideTooCloseText = "FIBER SAG",
	NetGuideTooFarText = "TOO TIGHT",
	NetGuidePinText = "HOLD PIN",
	NetGuideHareText = "HARE READY!",
	NetGuidanceBroadcastInterval = 0.18,
	ScoreReasonDropText = "DROP!",
	ScoreReasonOutText = "OUT!",
	ScoreReasonTooFarText = "TOO FAR!",
	ScoreReasonHareText = "HARE POINT!",
	HareCameraKick = 1.25,
	HareComboCameraKick = 1.75,
	NormalHitCameraKick = 0.34,
	MobileNetGuideYLandscape = 0.665,
	MobileNetGuideYPortrait = 0.785,
	MobileNetGuideBgTransparencyLandscape = 0.56,

	-- v0.5.1 Mobile Landscape & UI Fix.
	PreferLandscape = true,
	ShowRotateHint = true,
	MobileRotateHintNonBlocking = true,
	MobileRotateHintText = "Best in landscape",
	MobileHintFadeDelay = 3.5,
	MobileScoreYLandscape = 0.105,
	MobileScoreYPortrait = 0.095,
	MobileMessageYLandscape = 0.215,
	MobileMessageYPortrait = 0.205,
	MobileSubMessageYLandscape = 0.315,
	MobileSubMessageYPortrait = 0.300,
	MobileHintYLandscape = 0.895,
	MobileHintYPortrait = 0.865,
	MobileNetGuideWidthLandscape = 0.44,
	MobileNetGuideWidthPortrait = 0.72,
	MobilePinButtonScaleLandscape = 0.145,
	MobilePinButtonScalePortrait = 0.205,
	MobilePinButtonXLandscape = 0.905,
	MobilePinButtonYLandscape = 0.730,
	MobilePinButtonXPortrait = 0.835,
	MobilePinButtonYPortrait = 0.745,
	ShowPinButtonHelper = false,
	HidePinButtonHintLandscape = true,
	GhostPartnerVisible = false,
	GhostPartTransparency = 1,
	GhostPartSize = 0.55,
	MobileCameraHeightLandscape = 52,
	MobileCameraBackLandscape = 48,
	MobileCameraFovLandscape = 64,
	MobileCameraHeightPortrait = 92,
	MobileCameraBackPortrait = 76,
	MobileCameraFovPortrait = 66,
	PlaytestProfiles = {
		Solo = "LivePreset=Solo: ghost and CPU fill enabled, starts with 1 player",
		TwoPlayer = "LivePreset=TwoPlayer: ghost and CPU fill enabled, starts with 2 players",
		FourPlayer = "LivePreset=FourPlayer: ghost and CPU fill disabled, starts only with 4 humans",
	},
}

local livePresetName = Config.LivePreset or "Solo"
local livePreset = Config.LivePresets[livePresetName]
if not livePreset then
	error(("[GameConfig] Unknown LivePreset %q. Use Solo, TwoPlayer, or FourPlayer."):format(tostring(livePresetName)))
end

for key, value in pairs(livePreset) do
	Config[key] = value
end
Config.ActiveLivePreset = livePresetName

return Config
